version: "3.7"
x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "True"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
  AIRFLOW__DAG_DEFAULT_VIEW: graph

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_server
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  PostgresSQL:
    image: postgres:latest
    restart: always
    container_name: PostgresSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sminaya
      POSTGRES_PASSWORD: dDihi564
      POSTGRES_DB: LandingZone
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sergiosanh1907@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dDihi564
    ports:
      - "8081:80"
    depends_on:
      - PostgresSQL


  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
  init:
    image: apache/airflow:1.10.10
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: >
      -c "airflow list_users || (airflow initdb
      && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow)"
    restart: on-failure
  webserver:
    image: apache/airflow:1.10.10
    ports:
      - 8080:8080
    environment:
      <<: *airflow-environment
    depends_on:
      - init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "airflow webserver"
    restart: always
  scheduler:
    image: apache/airflow:1.10.10
    environment:
      <<: *airflow-environment
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "airflow scheduler"
    restart: always


    
volumes:
  postgres-db-volume:
  clickhouse_data: